name: CI

on:
    push:
        branches:
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: php-actions/composer@v6
            - uses: php-actions/phpunit@v4
            
            - name: Run Tests
            - run: php bin/phpunit